/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque/index'
import { Route as AuthenticatedEstoqueNovoRouteImport } from './routes/_authenticated/estoque/novo'
import { Route as AuthenticatedEstoqueIdRouteImport } from './routes/_authenticated/estoque/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueNovoRoute =
  AuthenticatedEstoqueNovoRouteImport.update({
    id: '/estoque/novo',
    path: '/estoque/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueIdRoute = AuthenticatedEstoqueIdRouteImport.update({
  id: '/estoque/$id',
  path: '/estoque/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/_authenticated/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/estoque/$id' | '/estoque/novo' | '/estoque/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/estoque/$id' | '/estoque/novo' | '/estoque'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/estoque/$id'
    | '/_authenticated/estoque/novo'
    | '/_authenticated/estoque/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/novo': {
      id: '/_authenticated/estoque/novo'
      path: '/estoque/novo'
      fullPath: '/estoque/novo'
      preLoaderRoute: typeof AuthenticatedEstoqueNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/$id': {
      id: '/_authenticated/estoque/$id'
      path: '/estoque/$id'
      fullPath: '/estoque/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEstoqueIdRoute: typeof AuthenticatedEstoqueIdRoute
  AuthenticatedEstoqueNovoRoute: typeof AuthenticatedEstoqueNovoRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEstoqueIdRoute: AuthenticatedEstoqueIdRoute,
  AuthenticatedEstoqueNovoRoute: AuthenticatedEstoqueNovoRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
