/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedMetasIndexRouteImport } from './routes/_authenticated/metas/index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro/index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque/index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores/index'
import { Route as AuthenticatedFinanceiroPorTipoRouteImport } from './routes/_authenticated/financeiro/por-tipo'
import { Route as AuthenticatedFinanceiroMargemRouteImport } from './routes/_authenticated/financeiro/margem'
import { Route as AuthenticatedFinanceiroDreRouteImport } from './routes/_authenticated/financeiro/dre'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro/despesas'
import { Route as AuthenticatedEstoqueNovoRouteImport } from './routes/_authenticated/estoque/novo'
import { Route as AuthenticatedEstoqueIdRouteImport } from './routes/_authenticated/estoque/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMetasIndexRoute = AuthenticatedMetasIndexRouteImport.update({
  id: '/metas/',
  path: '/metas/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroPorTipoRoute =
  AuthenticatedFinanceiroPorTipoRouteImport.update({
    id: '/financeiro/por-tipo',
    path: '/financeiro/por-tipo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroMargemRoute =
  AuthenticatedFinanceiroMargemRouteImport.update({
    id: '/financeiro/margem',
    path: '/financeiro/margem',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroDreRoute =
  AuthenticatedFinanceiroDreRouteImport.update({
    id: '/financeiro/dre',
    path: '/financeiro/dre',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/financeiro/despesas',
    path: '/financeiro/despesas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueNovoRoute =
  AuthenticatedEstoqueNovoRouteImport.update({
    id: '/estoque/novo',
    path: '/estoque/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueIdRoute = AuthenticatedEstoqueIdRouteImport.update({
  id: '/estoque/$id',
  path: '/estoque/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/margem': typeof AuthenticatedFinanceiroMargemRoute
  '/financeiro/por-tipo': typeof AuthenticatedFinanceiroPorTipoRoute
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/metas/': typeof AuthenticatedMetasIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/margem': typeof AuthenticatedFinanceiroMargemRoute
  '/financeiro/por-tipo': typeof AuthenticatedFinanceiroPorTipoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/metas': typeof AuthenticatedMetasIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/_authenticated/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/_authenticated/financeiro/margem': typeof AuthenticatedFinanceiroMargemRoute
  '/_authenticated/financeiro/por-tipo': typeof AuthenticatedFinanceiroPorTipoRoute
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/metas/': typeof AuthenticatedMetasIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/estoque/$id'
    | '/estoque/novo'
    | '/financeiro/despesas'
    | '/financeiro/dre'
    | '/financeiro/margem'
    | '/financeiro/por-tipo'
    | '/colaboradores/'
    | '/configuracoes/'
    | '/estoque/'
    | '/financeiro/'
    | '/metas/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/estoque/$id'
    | '/estoque/novo'
    | '/financeiro/despesas'
    | '/financeiro/dre'
    | '/financeiro/margem'
    | '/financeiro/por-tipo'
    | '/colaboradores'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/metas'
    | '/relatorios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/estoque/$id'
    | '/_authenticated/estoque/novo'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/financeiro/dre'
    | '/_authenticated/financeiro/margem'
    | '/_authenticated/financeiro/por-tipo'
    | '/_authenticated/colaboradores/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/estoque/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/metas/'
    | '/_authenticated/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metas/': {
      id: '/_authenticated/metas/'
      path: '/metas'
      fullPath: '/metas/'
      preLoaderRoute: typeof AuthenticatedMetasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/por-tipo': {
      id: '/_authenticated/financeiro/por-tipo'
      path: '/financeiro/por-tipo'
      fullPath: '/financeiro/por-tipo'
      preLoaderRoute: typeof AuthenticatedFinanceiroPorTipoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/margem': {
      id: '/_authenticated/financeiro/margem'
      path: '/financeiro/margem'
      fullPath: '/financeiro/margem'
      preLoaderRoute: typeof AuthenticatedFinanceiroMargemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/dre': {
      id: '/_authenticated/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/financeiro/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/novo': {
      id: '/_authenticated/estoque/novo'
      path: '/estoque/novo'
      fullPath: '/estoque/novo'
      preLoaderRoute: typeof AuthenticatedEstoqueNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/$id': {
      id: '/_authenticated/estoque/$id'
      path: '/estoque/$id'
      fullPath: '/estoque/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEstoqueIdRoute: typeof AuthenticatedEstoqueIdRoute
  AuthenticatedEstoqueNovoRoute: typeof AuthenticatedEstoqueNovoRoute
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFinanceiroDreRoute: typeof AuthenticatedFinanceiroDreRoute
  AuthenticatedFinanceiroMargemRoute: typeof AuthenticatedFinanceiroMargemRoute
  AuthenticatedFinanceiroPorTipoRoute: typeof AuthenticatedFinanceiroPorTipoRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
  AuthenticatedMetasIndexRoute: typeof AuthenticatedMetasIndexRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEstoqueIdRoute: AuthenticatedEstoqueIdRoute,
  AuthenticatedEstoqueNovoRoute: AuthenticatedEstoqueNovoRoute,
  AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
  AuthenticatedFinanceiroDreRoute: AuthenticatedFinanceiroDreRoute,
  AuthenticatedFinanceiroMargemRoute: AuthenticatedFinanceiroMargemRoute,
  AuthenticatedFinanceiroPorTipoRoute: AuthenticatedFinanceiroPorTipoRoute,
  AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
  AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  AuthenticatedMetasIndexRoute: AuthenticatedMetasIndexRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
